config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :cash_books
  resources :citizens do
    member do
      get :edit_request
      get :activate_citizen
      put :permit_request
    end
    collection do
      get :requests
      get :verify_application
      get :verify_citizen
    end
  end

  resources :others_certificates do
    member do
      get :activate
    end
    collection do
      get :requests
      get :verify_application
      get :verify_certificate
    end
  end

  resources :warishes do
    member do
      get :edit_request
      get :activate_warish
      put :permit_request
    end

    collection do
      get :requests
      get :verify_application
      get :verify_warish
    end
  end

  get 'warishes/show_by_tracking_id/:id' => 'warishes#show_by_tracking_id', as: :show_by_tracking_warishes
  get 'citizens/show_by_tracking_id/:id' => 'citizens#show_by_tracking_id', as: :show_by_tracking_citizens
  get 'others_certificates/show_by_tracking_id/:id' => 'others_certificates#show_by_tracking_id', as: :show_by_tracking_certificate

  resources :citizen_requests do
    collection do
      get :search
    end
  end

  resources :forms do
    collection do
      get :tax_or_rate_form
      get :others_form
    end
  end

  resources :collection_moneys

  resources :tax_or_rate_collections do
    collection do
      get :report
    end
  end
  resources :others_collections
  resources :trade_licenses
  resources :profiles

  resources :trade_organizations, shallow: true do

    member do
      get :renew
      post :create_trade_license
      get :print_money_recipt
    end

    collection do
      get :verify
    end
  end

  resources :expenses do
    collection do
      get :report
    end
  end

  get 'trade_organizations/:id/trade_license/:license_id/edit' => 'trade_organizations#edit_license',
      as: :edit_trade_org_trade_license

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  namespace :api do
    resources :divisions do
      member do
        get :districts
      end
    end

    resources :districts do
      member do
        get :upazilas
      end
    end

    resources :upazilas do
      member do
        get :unions
      end
    end

    resources :unions

  end

end

app/models/others_certificate.rb
class OthersCertificate < ActiveRecord::Base
  include ApplicationHelper, UnionHelper, Certificatable

  after_create :save_tracking_id, :save_certificate_no
  has_many :work_infos, dependent: :destroy
  has_many :freedom_fighters, dependent: :destroy
  has_many :relationships, dependent: :destroy

  accepts_nested_attributes_for :work_infos, allow_destroy: true
  accepts_nested_attributes_for :freedom_fighters, allow_destroy: true
  accepts_nested_attributes_for :relationships, allow_destroy: true

  validates :certificate_type, presence: true
  
  def save_certificate_no
    return if self.pending? || self.certifcate_no.present?

    cer_no = OthersCertificate.where(union_id: self.union.id).count(:certifcate_no)
    cer_no = cer_no + 1
    cer = get_unique_certificate_no cer_no
    self.update_attributes(:certifcate_no => cer)
  end

  def save_tracking_id
    return if self.active? || self.tracking_no.present?

    trac_no = OthersCertificate.where(union_id: self.union.id).count(:tracking_no)
    trac_id = "#{self.union.union_code}S#{current_year_month_day.to_s}#{trac_no.to_s}"
    self.update_attributes(:tracking_no => trac_id)
  end

  def work_info
    @work_info ||= self.work_infos.info(current_lang).first
    @work_info
  end

  def freedom_fighter
    @freedom_fighter ||= self.freedom_fighters.with_lang(current_lang).first
    @freedom_fighter
  end

  def relationship
    @relationship ||= self.relationships.with_lang(current_lang).first
    @relationship
  end

  def remove_dependents
    self.work_infos.update_all({status: :deleted}) if self.work_infos.present?
    self.freedom_fighters.update_all({status: :deleted}) if self.freedom_fighters.present?
    self.relationships.relationships({status: :deleted}) if self.relationships.present?
  end

  def template
    return 'others_certificates/pdf/no_remarried.pdf.erb' if self.certificate_type == 'no_remarried'
    return 'others_certificates/pdf/unmarried.pdf.erb' if self.certificate_type == 'unmarried'
    return 'others_certificates/pdf/married.pdf.erb' if self.certificate_type == 'married'
    return 'others_certificates/pdf/unemployed.pdf.erb' if self.certificate_type == 'unemployed'
    return 'others_certificates/pdf/landless.pdf.erb' if self.certificate_type == 'landless'
    return 'others_certificates/pdf/non_solvent.pdf.erb' if self.certificate_type == 'non_solvent'
    return 'others_certificates/pdf/orphan.pdf.erb' if self.certificate_type == 'orphan'
    return 'others_certificates/pdf/freedom_fighter.pdf.erb' if self.certificate_type == 'freedom_fighter'
    return 'others_certificates/pdf/income.pdf.erb' if should_show_work_info? self.certificate_type
    return 'others_certificates/pdf/only_widow.pdf.erb' if self.certificate_type == 'only_widow'
    return 'others_certificates/pdf/permanent_citizen.pdf.erb' if self.certificate_type == 'permanent_citizen'
    return 'others_certificates/pdf/same_name.pdf.erb' if self.certificate_type == 'same_name'
    return 'others_certificates/pdf/relationship.pdf.erb' if self.certificate_type == 'relationship'
    return 'others_certificates/pdf/orphan.pdf.erb' if self.certificate_type == 'orphan'
    return 'others_certificates/pdf/address_change.pdf.erb' if self.certificate_type == 'address_change'
  end

  private

  def get_unique_certificate_no(sl_no)
    cer_no = "#{self.union.union_code}S#{current_year.to_s}#{sl_no.to_s}"
    certificate = OthersCertificate.find_by_certifcate_no(cer_no)
    return cer_no if certificate.blank?
    return get_unique_certificate_no(sl_no + 1)
  end

end

app/controllers/others_certificates_controller.rb
class OthersCertificatesController < InheritedResources::Base
  require 'barby'
  require 'barby/barcode'
  require 'barby/barcode/qr_code'
  require 'barby/outputter/png_outputter'

  include ApplicationHelper, UnionHelper
  before_filter :authenticate_user!, only: [:index, :requests, :no_remarried, :activate_certificate]
  load_and_authorize_resource only: [:index, :requests, :show, :activate_certificate]

  def new
    @others_certificate = OthersCertificate.new
    @others_certificate.build_contact_address
    @others_certificate.build_citizen_basic
    if !user_signed_in?
      @others_certificate.build_image_attachment
    end

    @others_certificate.basic_infos.build(lang: current_lang)
    @others_certificate.addresses.build(address_type: :present, lang: current_lang)
    @others_certificate.addresses.build(address_type: :permanent, lang: current_lang)
    @c_type ||= params[:c_type]

    if should_show_work_info? @c_type
      @others_certificate.work_infos.build(lang: current_lang)
    end

    if @c_type == 'freedom_fighter'
      @others_certificate.freedom_fighters.build(lang: current_lang)
    end

    if @c_type == 'relationship'
      @others_certificate.relationships.build(lang: current_lang)
    end

  end

  def create
    @others_certificate = OthersCertificate.new(others_certificate_params)
    @c_type = @others_certificate.certificate_type
    respond_to do |format|
      if @others_certificate.save
        format.html { redirect_to user_signed_in? ? @others_certificate : public_certificate_path(@others_certificate), notice: get_notice }
        format.json { render :no_remarried, status: :created, location: @citizen }
      else
        @others_certificate.build_image_attachment if @others_certificate.image_attachment.blank?
        format.html { render :new,c_ype: @c_type }
        format.json { render json: @others_certificate.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit
    @others_certificate = current_user.others_certificates.find(params[:id])
    @c_type = @others_certificate.certificate_type
  end

  def index
    @others_certificates = current_user.others_certificates.where(status: :active)
                               .order('updated_at desc')
                               .page(params[:page])
                               .per(10)

    @others_certificates = @others_certificates.where("certifcate_no like :search", search: "%#{params[:q]}%") if params[:q].present?

    respond_to do |format|
      format.html
    end
  end


  def show
    @others_certificate = current_user.others_certificates.find(params[:id])
    @barcode = barcode_output(@others_certificate) if params[:format] == 'pdf'
    @c_type = @others_certificate.certificate_type

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => file_name,
               :template => @others_certificate.template,
               :layout => 'pdf.html.erb',
               :disposition => 'attachment',
               page_size: 'A4',
               :show_as_html => params[:debug].present?,
               margin: {top: 8, # default 10 (mm)
                        bottom: 0,
                        left: 5,
                        right: 5},
               dpi: '300'
      end
    end
  end

  def barcode_output(others_certificate)
    barcode_string = others_certificate.barcode
    barcode = Barby::QrCode.new(barcode_string, level: :q, size: 9)

    # PNG OUTPUT
    base64_output = Base64.encode64(barcode.to_png({xdim: 4}))
    "data:image/png;base64,#{base64_output}"
  end


  def show_by_tracking_id
    @others_certificate = OthersCertificate.find_by_tracking_no(params[:id])
  end


  def requests
    @others_certificates = current_user.others_certificates.where(status: :pending)
                               .order('updated_at desc')
                               .page(params[:page])
                               .per(10)

    @others_certificates = @others_certificates.where("tracking_no like :search", search: "%#{params[:q]}%") if params[:q].present?

    respond_to do |format|
      format.html
    end
  end

  def verify_application
    @others_certificate = OthersCertificate.find_by_tracking_no(params[:q]) if params[:q]
    # where status in
    respond_to do |format|
      format.html
      format.js
    end
  end

  def verify_certificate
    @others_certificate = OthersCertificate.find_by_certifcate_no(params[:q]) if params[:q]
    # where status in
    respond_to do |format|
      format.html
      format.js
    end
  end

  def activate
    @others_certificate = current_user.others_certificates.find(params[:id])
    @others_certificate.activate
    redirect_to @others_certificate, notice: 'Certificate was successfully activated.'
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @others_certificate = current_user.others_certificates.find(params[:id])
    @others_certificate.remove
    respond_to do |format|
      format.html { redirect_to others_certificates_url, notice: 'Certificate was successfully deleted' }
      format.json { head :no_content }
    end
  end

  private

  def file_name
    pdf_file_name 'certificate_' << @others_certificate.union_code
  end


  def public_certificate_path(oc)
    return show_by_tracking_certificate_path(oc.tracking_no)
  end

  def get_notice
    user_signed_in? ? 'Certificate was successfully created.' : 'আপনার আবেদনটি সাবমিট করা হয়েছে । ভবিষ্যৎ অনুসন্ধানের জন্য ট্র্যাকিং নম্বরটি সংগ্রহে রাখুন ।'
  end

  def others_certificate_params
    params.require(:others_certificate).permit(:union_id, :certificate_type, :status,
                                               work_infos_attributes: [:id, :for_whom_others, :annual_income, :income_in_bangla,
                                                                       :work_title, :workplace_name, :for_whom_id, :lang, :income_type],
                                               basic_infos_attributes: [:id, :name,:nick_name,:fathers_name, :spouse_name,
                                                                        :mothers_name, :date_of_birth,:fathers_death_date,:lang],
                                               addresses_attributes: [:id, :village, :road, :word_no, :district, :upazila,
                                                                      :post_office, :address_type, :lang],
                                               contact_address_attributes: [:id, :mobile_no, :email],
                                               citizen_basic_attributes: [:id, :nid, :birthid, :dob, :gender,
                                                                          :maritial_status_id, :citizenship_state_id,
                                                                          :religion_id],
                                               image_attachment_attributes: [:id, :photo],
                                               freedom_fighters_attributes:[:id,:red_book_no,:indian_no,:gazette_no,:lang],
                                               relationships_attributes:[:id,:to_whom,:person_title,:relation,:relation_type,:lang])
  end


end

app/helpers/others_certificates_helper.rb
module OthersCertificatesHelper

  def cer_label(c_type)
    case c_type
      when 'unmarried'
        'অবিবাহিত সনদের আবেদন'
      when 'married'
        'বিবাহিত সনদের আবেদন'
      when 'no_remarried'
        'পুনঃ বিবাহ না হওয়ার সনদের আবেদন'
      when 'unemployed'
        'বেকারত্ব সনদের আবেদন'
      when 'non_solvent'
        'আর্থিক অসচ্ছলতার সনদ'
      when 'rename'
        'একি  নামের প্রত্যয়ন পত্রের আবেদন'
      when 'only_widow'
        'একমাত্র বৈধ বিধবা স্ত্রীর সনদপত্র'
      when 'landless'
        'ভূমিহীন সনদের আবেদন'
      when 'annual_income'
        'বার্ষিক আয়ের প্রত্যয়ন পত্রের আবেদন'
      when 'permanent_citizen'
        'স্থায়ী বাসিন্দার সনদ'
      when 'same_name'
        'দুই নামে একই ব্যক্তির সনদপত্র'
      when 'freedom_fighter'
        'মুক্তিযোদ্ধা সনদের আবেদন'
      when 'income_monthly'
        'মাসিক আয়ের সনদপত্র'
      when 'income_yearly'
        'বাৎসরিক আয়ের সনদপত্র'
      when 'relationship'
        'সম্পর্কের সনদপত্র'
      when 'orphan'
        'এতিম সনদপত্র'
      when 'address_change'
        'ঠিকানা পরিবর্তনের প্রত্যয়ন পত্র'
    end
  end

  def cer_label_type(c_type)
    case c_type
      when 'unmarried'
        'অবিবাহিত সনদ'
      when 'married'
        'বিবাহিত সনদ'
      when 'landless'
        'ভূমিহীন'
      when 'no_remarried'
        'পুনঃ বিবাহ না'
      when 'unemployed'
        'বেকারত্ব'
      when 'non_solvent'
        'আর্থিক অসচ্ছল'
      when 'rename'
        'একি নামের প্রত্যয়ন'
      when 'only_widow'
        'বৈধ বিধবা স্ত্রী'
      when 'annual_income'
        'বার্ষিক আয়ের প্রত্যয়ন'
      when 'permanent_citizen'
        'স্থায়ী বাসিন্দা'
      when 'same_name'
        'দুই নামে একই'
      when 'freedom_fighter'
        'মুক্তিযোদ্ধা'
      when 'income_yearly'
        'বাৎসরিক আয়'
      when 'income_monthly'
        'মাসিক আয়'
      when 'relationship'
        'সম্পর্ক'
      when 'orphan'
        'এতিম'
      when 'address_change'
        'ঠিকানা পরিবর্তন'
    end
  end

  def cer_husband_wife(cb)
    return '' if cb.maritial_status.unmarried? || cb.maritial_status.married? || cb.other?
    return 'স্বামীর' if cb.female?
    return 'স্ত্রীর' if cb.male?
    return 'সঙ্গীর' if cb.other?
  end

  def cer_maritial_state(cb)
    return '' if cb.maritial_status.unmarried? || cb.maritial_status.married? || cb.other?
    return 'মৃত্যুর পর' if cb.maritial_status.widow?
    return 'সাথে বিচ্ছেদের পর' if cb.maritial_status.divorced?
  end

  def who(work_info)
    return work_info.for_whom_others if work_info.for_whom.other?
    work_info.for_whom.who_in_bangla
  end

  def income_whom(work_info)
    return '' if work_info.blank?
    if work_info.for_whom.own?
      return "তিনি একজন #{work_info.work_title}"
    end

    if work_info.for_whom.other?
      who = work_info.for_whom_others
    else
      who = work_info.for_whom.who_in_bangla
    end

    return "তাহার #{who} একজন #{work_info.work_title}"
  end

  def income_type(work_info)
    return String.new if work_info.blank?

    case work_info.income_type
      when 'income_monthly'
        'মাসিক আয়ের সনদপত্র'
      when 'income_yearly'
        'বাৎসরিক আয়ের সনদপত্র'
    end
  end

  def income_money(work_info)
    return '' if work_info.blank?

    type = String.new
    case work_info.income_type
      when 'income_monthly'
        type = 'মাসিক'
      when 'income_yearly'
        type = 'বাৎসরিক'
    end

    if work_info.for_whom.own?
      return "তাহার #{type} আয় #{bangla_number(number_with_delimiter(work_info.annual_income))}( #{work_info.income_in_bangla} ) টাকা"
    end

    return "তাহার #{who(work_info)}র #{type} আয় #{bangla_number(number_with_delimiter(work_info.annual_income))} (#{work_info.income_in_bangla}) টাকা"
  end

end

app/views/others_certificates/_certificates.html.erb
<% if certificates %>
    <table class="table table-bordered table-striped">
      <thead>

      <tr>
        <% if show_tracking %>
            <th>Tracking Id</th>
        <% end %>
        <% if show_certificate_no %>
            <th>Certificate No</th>
        <% end %>

        <th>NID/BirthId</th>
        <th>Type</th>
        <th>Name</th>
        <th>Father's Name</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>

      <% certificates.each do |others_certificate| %>
          <tr>
            <% if show_tracking %>
                <td><%= link_to(others_certificate.tracking_no, others_certificate_path(others_certificate)) %></td>
            <% end %>


            <% if show_certificate_no %>
                <td><%= link_to(others_certificate.certifcate_no, others_certificate_path(others_certificate)) %></td>
            <% end %>

            <% if others_certificate.citizen_basic.present? %>
                <td><%= link_to(others_certificate.citizen_basic.nid_or_birthid, others_certificate_path(others_certificate)) %></td>
            <% else %>
                <td></td>
            <% end %>

            <td><%= cer_label_type(others_certificate.certificate_type) %></td>

            <% if others_certificate.basic_information.present? %>
                <td><%= link_to(others_certificate.basic_information.name, others_certificate_path(others_certificate)) %></td>
                <td><%= link_to(others_certificate.basic_information.fathers_name, others_certificate_path(others_certificate)) %></td>
            <% else %>
                <td></td>
                <td></td>
            <% end %>

            <td>
              <%= link_to('Edit', edit_others_certificate_path(others_certificate)) %>
              <%= link_to('Delete', others_certificate_path(others_certificate), method: :delete, data: { confirm: 'Are you sure?' }) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate certificates %>
<% end %>

app/views/others_certificates/_form.html.erb
<div id="signupbox" class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <div class="panel panel-info">
    <div class="panel-heading">
      <div class="panel-title"><%= cer_label(@c_type) %></div>
    </div>

    <div class="panel-body">

      <div class="container-page">
        <div class="col-md-12">
          <%= form_for @others_certificate do |f| %>

            <% if @others_certificate.errors.any? %>
              <div id="signupalert" class="alert alert-danger">
                <h2><%= pluralize(@others_certificate.errors.count, "error") %> prohibited this user from being
                  saved:</h2>
                <ul>
                  <% @others_certificate.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <% if !user_signed_in? %>

              <% if f.object.new_record? %>
                <span class=" text-center help-block">নাগরিকত্ব অথবা জন্ম নিবন্ধন এর স্ক্যান করা ছবি</span>
                <div class="form-group col-lg-12">
                  <%= f.fields_for :image_attachment do |p| %>
                    <%= p.file_field :photo, accept: 'image/png,image/jpeg', class: "form-control" %>
                  <% end %>
                </div>
              <% end %>
            <% end %>

            <%= f.fields_for :basic_infos do |bi| %>
              <%= render partial: 'layouts/basic_information_compact', locals: {f: bi, is_warish: false} %>
            <% end %>

            <% if user_signed_in? %>
              <%= f.hidden_field :union_id, :value => current_user.union.id %>
            <% else %>
              <div class="form-group col-lg-6">
                <label>ইউনিয়ন</label>
                <%= f.collection_select :union_id, Union.all, :id, :name_in_bng, {}, {class: "form-control"} %>
              </div>
            <% end %>

            <%= f.hidden_field :status, :value => user_signed_in? ? :active : :pending %>

            <%= f.hidden_field :certificate_type, value: @c_type %>

            <%= f.fields_for :citizen_basic do |cb| %>
              <%= render partial: 'layouts/citizen_basic_compact', locals: {f: cb} %>
            <% end %>

            <% if should_show_work_info? @c_type %>
              <%= f.fields_for :work_infos do |wi| %>
                <%= render partial: 'layouts/work_info', locals: {f: wi} %>
              <% end %>
            <% end %>

            <% if should_show_freedom_fighter? @c_type %>
              <%= f.fields_for :freedom_fighters do |ff| %>
                <%= render partial: 'layouts/freedom_fighter_info', locals: {f: ff} %>
              <% end %>
            <% end %>

            <% if should_show_relationship? @c_type %>
              <%= f.fields_for :relationships do |rs| %>
                <%= render partial: 'layouts/relationship_info', locals: {f: rs} %>
              <% end %>
            <% end %>

            <%= f.fields_for :addresses do |ad| %>
              <%= render partial: 'layouts/address_compact', locals: {f: ad} %>
            <% end %>

            <%= f.fields_for :contact_address do |ca| %>
              <%= render partial: 'layouts/contact_address_compact', locals: {f: ca} %>
            <% end %>

            <div class="form-group">
              <!-- Button -->
              <div class="col-md-offset-4 col-md-4">
                <%= f.submit "দাখিল করুন", class: "btn btn-info" %>
              </div>
            </div>

            <div class="col-md-9">

              <% if user_signed_in? %>
                <% if f.object.new_record? || f.object.active? %>
                  <%= link_to 'Back', others_certificates_path %>
                <% else %>
                  <%= link_to 'Back', requests_others_certificates_path %>
                <% end %>
              <% else %>
                <%= link_to 'Back', root_path %>
              <% end %>
            </div>

          <% end %>

        </div>

      </div>
    </div>
  </div>
</div>

app/views/others_certificates/_users_actions.html.erb
<div class="row">
  <div class="col-xs-12">

    <% if @others_certificate.active? %>
        <%= link_to 'Back', others_certificates_path, class: "btn btn-primary" %>
        <%= link_to 'Print Certificate With Sign', others_certificate_path(@others_certificate, format: 'pdf', sign: true), class: "btn btn-success" %>
        <%= link_to 'Print Certificate W/O Sign', others_certificate_path(@others_certificate, format: 'pdf', sign: false), class: "btn btn-warning" %>
        <% if @others_certificate.contact_address.email.present? %>
          <%= link_to 'Send Email','#', class: "btn btn-success" %>
        <% end%>
        <%= link_to 'Deactivate','#', class: "btn btn-warning" %>
    <% end %>

    <% if @others_certificate.pending? %>
        <%= link_to 'Activate', activate_others_certificate_path(@others_certificate), class: "btn btn-info btn-default" %>
        <%= link_to 'Back', requests_others_certificates_path, class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/others_certificates/edit.html.erb
<%= render 'form' %>

app/views/others_certificates/index.html.erb
<div class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <p id="notice"><%= notice %></p>

  <h1>অন্যান্য সনদসমূহ</h1>

  <div class="row">
    <%= form_tag(others_certificates_path, method: :get) do %>
        <div class="form-group col-md-10">
          <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "অন্যান্য সনদ নম্বরটি প্রবেশ করুন" %>
        </div>
        <div class="form-group col-md-2">
          <%= submit_tag 'খোঁজ করুন', class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= render 'certificates', certificates: @others_certificates, show_tracking: false, show_certificate_no: true %>
    </div>
  </div>
</div>

app/views/others_certificates/new.html.erb
<%= render 'form' %>

app/views/others_certificates/requests.html.erb
<div class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <p id="notice"><%= notice %></p>

  <h1>অন্যান্য সনদের আবেদনকারী</h1>

  <div class="row">
    <%= form_tag(requests_others_certificates_path, method: :get) do %>
        <div class="form-group col-md-10">
          <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "ট্র্যাকিং নম্বরটি প্রবেশ করুন" %>
        </div>
        <div class="form-group col-md-2">
          <%= submit_tag 'খোঁজ করুন', class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= render 'certificates', certificates: @others_certificates, show_tracking: true, show_certificate_no: false %>
    </div>
  </div>

</div>

app/views/others_certificates/show.html.erb
<%= render 'show' %>

app/views/others_certificates/show_by_tracking_id.html.erb
<%= render 'show' %>

app/views/others_certificates/verify_application.html.erb
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-2 toppad">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">সনদের আবেদন যাচাই</h3>
    </div>

    <div class="panel-body">
      <div class="row">

        <%= form_tag(verify_application_others_certificates_path, method: :get, remote: true) do %>
            <div class="form-group col-md-10">
              <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "আপনার সনদের আবেদনের ট্র্যাকিং নম্বরটি প্রবেশ করুন" %>
            </div>
            <div class="form-group col-md-2">
              <%= submit_tag 'খোঁজ করুন', class: "btn btn-primary" %>
            </div>
        <% end %>
        <div id="results">
          <% if @others_certificate.present? %>
              <%= render @others_certificate %>
          <% end %>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/others_certificates/verify_application.js.erb
$("#results").html("<%= escape_javascript render("certificate") %>");

app/views/others_certificates/verify_certificate.html.erb
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-2 toppad">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">সনদ যাচাই</h3>
    </div>

    <div class="panel-body">
      <div class="row">

        <%= form_tag(verify_certificate_others_certificates_path, method: :get, remote: true) do %>
            <div class="form-group col-md-10">
              <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "আপনার সনদের নম্বরটি প্রবেশ করুন" %>
            </div>
            <div class="form-group col-md-2">
              <%= submit_tag 'খোঁজ করুন', class: "btn btn-primary" %>
            </div>
        <% end %>
        <div id="results">
          <% if @citizen.present? %>
              <%= render @citizen %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>