config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :cash_books
  resources :citizens do
    member do
      get :edit_request
      get :activate_citizen
      put :permit_request
    end
    collection do
      get :requests
      get :verify_application
      get :verify_citizen
    end
  end

  resources :others_certificates do
    member do
      get :activate
    end
    collection do
      get :requests
      get :verify_application
      get :verify_certificate
    end
  end

  resources :warishes do
    member do
      get :edit_request
      get :activate_warish
      put :permit_request
    end

    collection do
      get :requests
      get :verify_application
      get :verify_warish
    end
  end

  get 'warishes/show_by_tracking_id/:id' => 'warishes#show_by_tracking_id', as: :show_by_tracking_warishes
  get 'citizens/show_by_tracking_id/:id' => 'citizens#show_by_tracking_id', as: :show_by_tracking_citizens
  get 'others_certificates/show_by_tracking_id/:id' => 'others_certificates#show_by_tracking_id', as: :show_by_tracking_certificate

  resources :citizen_requests do
    collection do
      get :search
    end
  end

  resources :forms do
    collection do
      get :tax_or_rate_form
      get :others_form
    end
  end

  resources :collection_moneys

  resources :tax_or_rate_collections do
    collection do
      get :report
    end
  end
  resources :others_collections
  resources :trade_licenses
  resources :profiles

  resources :trade_organizations, shallow: true do

    member do
      get :renew
      post :create_trade_license
      get :print_money_recipt
    end

    collection do
      get :verify
    end
  end

  resources :expenses do
    collection do
      get :report
    end
  end

  get 'trade_organizations/:id/trade_license/:license_id/edit' => 'trade_organizations#edit_license',
      as: :edit_trade_org_trade_license

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  namespace :api do
    resources :divisions do
      member do
        get :districts
      end
    end

    resources :districts do
      member do
        get :upazilas
      end
    end

    resources :upazilas do
      member do
        get :unions
      end
    end

    resources :unions

  end

end

app/models/warish.rb
class Warish < ActiveRecord::Base
  include ApplicationHelper, UnionHelper,Certificatable
  has_many :warish_relations, dependent: :destroy

  accepts_nested_attributes_for :warish_relations, reject_if: :all_blank, allow_destroy: true

  after_create :save_tracking_id
  after_save :save_certificate_no

  def save_certificate_no
    return if self.pending? || self.warish_no.present?

    warsh_no = Warish.where(union_id: self.union.id).count(:warish_no)
    warsh_no = warsh_no + 1
    warsh = get_unique_certificate_no warsh_no
    self.update_attributes(:warish_no => warsh)
  end

  def remove_dependents
    self.warish_relations.update_all({status: :deleted}) if self.warish_relations.present?
  end


  def save_tracking_id
    return if self.active? || self.tracking_id.present?

    trac_no = Warish.where(union_id: self.union.id).count(:tracking_id)
    trac_id = "#{self.union.union_code}W#{current_year_month_day.to_s}#{trac_no.to_s}"
    self.update_attributes(:tracking_id => trac_id)
  end

  private

  def get_unique_certificate_no(sl_no)
    cer_no = "#{self.union.union_code}W#{current_year.to_s}#{sl_no.to_s}"
    warish = Warish.find_by_warish_no(cer_no)
    return cer_no if warish.blank?
    return get_unique_certificate_no(sl_no + 1)
  end



end

app/controllers/warishes_controller.rb
class WarishesController < InheritedResources::Base
  require 'barby'
  require 'barby/barcode'
  require 'barby/barcode/qr_code'
  require 'barby/outputter/png_outputter'

  include ApplicationHelper, UnionHelper
  before_filter :authenticate_user!, only: [:index, :requests, :show, :activate_warish]
  load_and_authorize_resource only: [:index, :requests, :show, :activate_warish]
  before_action :set_warish, only: [:show, :edit, :update, :destroy,:activate_warish]

  def new
    @warish = Warish.new
    @warish.build_contact_address
    @warish.build_citizen_basic
    if !user_signed_in?
      @warish.build_image_attachment
    end
    @warish.basic_infos.build(lang: current_lang)
    @warish.addresses.build(address_type: :present, lang: current_lang)
    @warish.addresses.build(address_type: :permanent, lang: current_lang)
    @warish.warish_relations.build
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @warish = Warish.new(warish_params)

    respond_to do |format|
      if @warish.save
        format.html { redirect_to user_signed_in? ? @warish : public_warish_path(@warish), notice: get_notice }
        format.json { render :show, status: :created, location: @warish }
      else
        @warish.build_image_attachment if @warish.image_attachment.blank?
        format.html { render :new }
        format.json { render json: @warish.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @warish.update(warish_params)
        format.html { redirect_to  @warish, notice: 'Warish was successfully updated.' }
        format.json { render :show, status: :ok, location: @warish }
      else
        format.html { render :edit }
        format.json { render json: @warish.errors, status: :unprocessable_entity }
      end
    end

  end


  def show_by_tracking_id
    @warish = Warish.find_by_tracking_id(params[:id])
  end

  def activate_warish
    @warish.activate
    redirect_to @warish, notice: 'Warish was successfully activated.'
  end

  def verify_application
    @warish = Warish.find_by_tracking_id(params[:q]) if params[:q]
    # where status in
    respond_to do |format|
      format.html
      format.js
    end
  end

  def verify_warish
    @warish = Warish.find_by_warish_no(params[:q]) if params[:q]
    # where status in
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @warishes = current_user.warishes.where(status: :active)
                    .order('updated_at desc')
                    .page(params[:page])
                    .per(10)

    @warishes = @warishes.where("warish_no like :search", search: "%#{params[:q]}%") if params[:q].present?

    respond_to do |format|
      format.html
    end
  end

  def requests
    @warishes = current_user.warishes.where(status: :pending)
                    .order('created_at asc')
                    .page(params[:page])
                    .per(10)
    @warishes = @warishes.where("tracking_id like :search", search: "%#{params[:q]}%") if params[:q].present?

    respond_to do |format|
      format.html
      format.json { render json: @citizens }
    end
  end

  def edit_request
    @warish = Warish.find(params[:id]);
  end

  #PUT
  def permit_request
    @warish = Warish.find(params[:id]);
    #@citizen.save_citizen_no

    respond_to do |format|
      if @warish.update(citizen_params)
        format.html { redirect_to requests_citizens_path, notice: 'Citizen was successfully updated' }
        format.json { render :show, status: :ok, location: @citizen }
      else
        format.html { render :edit_request }
        format.json { render json: @citizen.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @warish.remove
    respond_to do |format|
      format.html { redirect_to warishes_url, notice: 'Citizen was successfully deleted' }
      format.json { head :no_content }
    end
  end

  def show
    @barcode = barcode_output(@warish) if params[:format] == 'pdf'

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => file_name,
               :template => 'warishes/show.pdf.erb',
               :layout => 'pdf.html.erb',
               :disposition => 'attachment',
               page_size: 'A4',
               :show_as_html => params[:debug].present?,
               margin: {top: 8, # default 10 (mm)
                        bottom: 0,
                        left: 5,
                        right: 5},
               dpi: '300'
      end
    end
  end

  def barcode_output(warish)
    barcode_string = warish.barcode
    barcode = Barby::QrCode.new(barcode_string, level: :q, size: 9)

    # PNG OUTPUT
    base64_output = Base64.encode64(barcode.to_png({xdim: 4}))
    "data:image/png;base64,#{base64_output}"
  end


  private

  def set_warish
    @warish = current_user.warishes.find(params[:id])
  end

  def warish_params
    params.require(:warish).permit(:union_id, :status,
                                   warish_relations_attributes: [:id,:name, :age, :comment, :relation,:_destroy],
                                   basic_infos_attributes: [:id, :name, :fathers_name, :mothers_name, :date_of_birth,
                                                            :father_alive, :mother_alive, :lang],
                                   addresses_attributes: [:id, :village, :road, :word_no, :district, :upazila,
                                                          :post_office, :address_type, :lang],
                                   contact_address_attributes: [:id, :mobile_no, :email],
                                   citizen_basic_attributes: [:id, :nid, :birthid, :dob, :gender, :maritial_status_id,
                                                              :citizenship_state_id, :religion_id])
  end

  def file_name
    pdf_file_name 'warish_certificate_' << @warish.union_code
  end

  def get_notice
    user_signed_in? ? 'Warsih is successfully created.' : 'আপনার আবেদনটি সাবমিট করা হয়েছে । ভবিষ্যৎ অনুসন্ধানের জন্য ট্র্যাকিং নম্বরটি সংগ্রহে রাখুন ।'
  end

  def public_warish_path(warish)
    return show_by_tracking_warishes_path(warish.tracking_id)
  end

end

app/views/warishes/_form.html.erb
<div id="signupbox" class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <div class="panel panel-info">
    <div class="panel-heading">
      <div class="panel-title">ওয়ারিশ সনদের আবেদন</div>
    </div>
    <div class="panel-body">
      <%= form_for @warish do |f| %>

          <% if @warish.errors.any? %>
              <div id="signupalert" class="alert alert-danger">
                <h2><%= pluralize(@warish.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                  <% @warish.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <% if f.object.new_record?%>
              <div class="form-group col-lg-12">
                <%= f.fields_for :image_attachment do |p| %>
                    <span class=" text-center help-block">নাগরিকত্ব অথবা জন্ম নিবন্ধন এর স্ক্যান করা ছবি</span>
                    <%= p.file_field :photo, accept: 'image/png,image/jpeg', class: "form-control" %>
                <% end %>
              </div>
          <% end %>


          <%= f.fields_for :basic_infos do |bi| %>
              <%= render partial: 'layouts/basic_information_compact', locals: {f: bi, is_warish: true} %>
          <% end %>

          <% if user_signed_in? %>
              <%= f.hidden_field :union_id, :value => current_user.union.id %>
          <% else %>
              <div class="form-group col-lg-6">
                <label>ইউনিয়ন</label>
                <%= f.collection_select :union_id, Union.all, :id, :name_in_bng, {}, {class: "form-control"} %>
              </div>
          <% end %>

          <%= f.hidden_field :status, :value => user_signed_in? ? :active : :pending %>

          <%= f.fields_for :citizen_basic do |cb| %>
              <%= render partial: 'layouts/citizen_basic_compact', locals: {f: cb} %>
          <% end %>

          <div class="form-group col-lg-12">
            <div class="form-group">
              <h4 class="text-center"><u>ওয়ারিশগনের তালিকা </u></h4>
            </div>
          </div>

          <%= f.fields_for :warish_relations do |w| %>
              <%= render 'warish_relation_fields', f: w %>
          <% end %>

          <div class="form-group col-lg-12">
            <div class="form-group">
              <%= link_to_add_association 'নতুন ওয়ারিশ', f, :warish_relations, class: "btn btn-primary pull-right" %>
            </div>
          </div>

          <%= f.fields_for :addresses do |ad| %>
              <%= render partial: 'layouts/address_compact', locals: {f: ad} %>
          <% end %>

          <%= f.fields_for :contact_address do |ca| %>
              <%= render partial: 'layouts/contact_address_compact', locals: {f: ca} %>
          <% end %>

          <div class="form-group">
            <!-- Button -->
            <div class="col-md-offset-4 col-md-4">
              <%= f.submit "দাখিল করুন", class: "btn btn-info" %>
            </div>
          </div>
          <div class="col-md-9">

            <% if user_signed_in? %>
                <% if f.object.new_record? || f.object.active? %>
                    <%= link_to 'Back', warishes_path %>
                <% else %>
                    <%= link_to 'Back', requests_warishes_path %>
                <% end %>
            <% else %>
                <%= link_to 'Back', root_path %>
            <% end %>
          </div>
      <% end %>


    </div>
  </div>
</div>

app/views/warishes/_show.html.erb
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-2 toppad">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">ওয়ারিশের বিবরণ</h3>
    </div>

    <div class="panel-body">
      <% if @warish.image_attachment.present? %>
          <%= render partial: 'layouts/show_image', locals: {image_attachment: @citizen.image_attachment} %>
      <% end %>

      <% if @warish.pending? %>
          <div class="row">
            <div class="col-xs-2">
              <label> ট্র্যাকিং নম্বর:</label>
            </div>
            <div class="col-xs-10 pull-left">
              <p><%= @warish.tracking_id %></p>
            </div>
          </div>
      <% end %>
      <%= render partial: 'layouts/show_basic_info', locals: {person: @warish.basic_information} %>
      <%= render partial: 'layouts/show_citizen_info', locals: {person: @warish.citizen_basic} %>
      <%= render partial: 'layouts/show_address', locals: {address: @warish.present_address} %>
      <%= render partial: 'layouts/show_address', locals: {address: @warish.permanent_address} %>
      <%= render partial: 'layouts/show_contact_address', locals: {address: @warish.contact_address} %>

      <%= render 'warish_relations_show' %>

      <% if user_signed_in? %>
          <%= render 'users_actions' %>
      <% else %>
          <%= render 'public_actions' %>
      <% end %>

    </div>
  </div>
</div>

app/views/warishes/_warish.html.erb
<% if @warish.present? %>
    <div class="row">
      <div class="col-md-10 col-sm-offset-1">
        <p id="notice"><%= notice %></p>
        <% if @warish.image_attachment.present? %>
            <%= render partial: 'layouts/show_image', locals: {image_attachment: @warish.image_attachment} %>
        <% end %>

        <% if @warish.warish_no.present? %>
            <div class="row">
              <div class="col-xs-2">
                <label>নাগরিকত্ব নং:</label>
              </div>
              <div class="col-xs-10 pull-left">
                <p><%= @warish.warish_no %></p>
              </div>
            </div>
        <% end %>

        <% if @warish.pending? %>
            <div class="row">
              <div class="col-xs-2">
                <label> ট্র্যাকিং নম্বর:</label>
              </div>
              <div class="col-xs-10 pull-left">
                <p><%= @warish.tracking_id %></p>
              </div>
            </div>
        <% end %>

        <% if @warish.basic_information.present? %>
            <%= render partial: 'layouts/show_basic_info', locals: {person: @warish.basic_information} %>
        <% end %>

        <div class="row">
          <div class="col-xs-2">
            <label> ইউনিয়ন:</label>
          </div>
          <div class="col-xs-10 pull-left">
            <p><%= @warish.union_name_bng %></p>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-2">
            <label>উপজেলা:</label>
          </div>
          <div class="col-xs-10 pull-left">
            <p><%= @warish.upazila_name_bng %></p>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-2">
            <label> জেলা:</label>
          </div>
          <div class="col-xs-10 pull-left">
            <p><%= @warish.zila_name_bng %></p>
          </div>
        </div>

        <% if @warish.citizen_basic.present? %>
            <%= render partial: 'layouts/show_citizen_info', locals: {person: @warish.citizen_basic} %>
        <% end %>

        <div class="row">
          <div class="col-xs-2">
            <label>স্ট্যাটাস:</label>
          </div>
          <div class="col-xs-10">
            <p><%= @warish.status %></p>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-2">
            <label>তারিখ:</label>
          </div>
          <div class="col-xs-10">
            <p><%= @warish.created_at %></p>
          </div>
        </div>

      </div>
    </div>
<% else %>
    <p>No warish found</p>
<% end %>

app/views/warishes/_warish_relation.html.erb
<div class="form-group">
  <label for="nameInEng" class="col-md-3 control-label">নাম</label>
  <div class="col-md-9">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <label for="nameInEng" class="col-md-3 control-label">সম্পর্ক</label>
  <div class="col-md-9">
    <%= f.text_field :relation, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <label for="nameInEng" class="col-md-3 control-label">বয়স</label>
  <div class="col-md-9">
    <%= f.text_field :age, class: "form-control" %>
  </div>
</div>

app/views/warishes/_warish_relation_compact.html.erb
<div class="col-lg-12 table-responsive">
  <table class="table table-bordered table-hover table-sortable" id="tab_logic">
    <thead>
    <tr >
      <th class="text-center">নাম</th>
      <th class="text-center">সম্পর্ক</th>
      <th class="text-center">মন্তব্য</th>
      <th></th>
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <%= f.text_field :name, class: "form-control" %>
      </td>
      <td>
        <%= f.text_field :relation, class: "form-control" %>
      </td>
      <td>
        <%= f.text_field :comment, class: "form-control" %>
      </td>
      <td>
        <button name="del0" class='btn btn-danger glyphicon glyphicon-remove row-remove'></button>
      </td>
    </tr>
    </tbody>
  </table>
  <a id="add_row" class="btn btn-primary pull-right">নতুন ওয়ারিশ</a>
</div>

app/views/warishes/_warish_relation_fields.html.erb
<div class="col-lg-12 table-responsive nested-fields">
  <table class="table table-bordered" id="tab_logic">
    <thead>
    <tr>
      <th class="text-center">নাম</th>
      <th class="text-center">সম্পর্ক</th>
      <th class="text-center">মন্তব্য</th>
      <th></th>
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <%= f.text_field :name, class: "form-control" %>
      </td>
      <td>
        <%= f.text_field :relation, class: "form-control" %>
      </td>
      <td>
        <%= f.text_field :comment, class: "form-control" %>
      </td>
      <td>
        <%= link_to_remove_association '', f, class: 'btn btn-danger glyphicon glyphicon-remove row-remove' %>
      </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/warishes/_warishes.html.erb
<% if warishes %>
    <table class="table table-bordered table-striped">
      <thead>

      <tr>
        <% if show_tracking %>
            <th>Tracking Id</th>
        <% end %>
        <% if show_warish_no %>
            <th>Warish No</th>
        <% end %>
        <th>NID/BirthId</th>

        <th>Dead Person's Name</th>
        <th>Father's Name</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>

      <% warishes.each do |warish| %>
          <tr>
            <% if show_tracking %>
                <td><%= link_to(warish.tracking_id, warish_path(warish)) %></td>
            <% end %>


            <% if show_warish_no %>
                <td><%= link_to(warish.warish_no, warish_path(warish)) %></td>
            <% end %>

            <% if warish.citizen_basic.present? %>
                <td><%= link_to(warish.citizen_basic.nid_or_birthid, warish_path(warish)) %></td>
            <% else %>
                <td></td>
            <% end %>

            <% if warish.basic_information.present? %>
                <td><%= link_to(warish.basic_information.name, warish_path(warish)) %></td>
                <td><%= link_to(warish.basic_information.fathers_name, warish_path(warish)) %></td>
            <% else %>
                <td></td>
                <td></td>
            <% end %>

            <td>
              <%= link_to('Edit', edit_warish_path(warish)) %>
              <%= link_to('Delete',warish_path(warish), method: :delete, data: { confirm: 'Are you sure?' }) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate warishes %>
<% end %>

app/views/warishes/edit_request.html.erb
<div id="signupbox" class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <div class="panel panel-info">
    <div class="panel-heading">
      <div class="panel-title">নাগরিক ফরম</div>
    </div>
    <div class="panel-body">
      <%= form_for @citizen, html:{class: 'form-horizontal', method: :put },url: permit_request_citizen_path do |f| %>

          <% if @citizen.errors.any? %>
              <div id="signupalert"  class="alert alert-danger" >
                <h2><%= pluralize(@citizen.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                  <% @citizen.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>


          <div class="form-group">
            <label for="nameInEng" class="col-md-3 control-label">Name(English)*</label>
            <div class="col-md-9">
              <%= f.text_field :name_in_eng, class: "form-control", placeholder: "Name In English" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">বাংলা নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :name_in_bng, class: "form-control", placeholder: "Name In Bangla" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">বাবার নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :fathers_name, class: "form-control",placeholder: "In Bangla"  %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">মায়ের নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :mothers_name, class: "form-control",placeholder: "In Bangla" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">স্বামী/স্ত্রী নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :spouse_name, class: "form-control",placeholder: "In Bangla" %>
            </div>
          </div>

          <!-- Multiple Radios (inline) -->
          <div class="form-group">
            <label class="col-md-3 control-label" for="radios">লিঙ্গঃ</label>
            <div class="col-md-9">
              <label class="radio-inline" for="radios-0">
                <input type="radio" name="radios" id="radios-0" value="1" checked="checked">
                পুরুষ
              </label>
              <label class="radio-inline" for="radios-1">
                <input type="radio" name="radios" id="radios-1" value="2">
                মহিলা
              </label>
              <label class="radio-inline" for="radios-2">
                <input type="radio" name="radios" id="radios-2" value="3">
                অন্যান্য
              </label>

            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">গ্রামের নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :village, class: "form-control",placeholder: "In Bangla" %>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">ডাকঘরঃ</label>
            <div class="col-md-9">
              <%= f.text_field :post, class: "form-control",placeholder: "In Bangla" %>
            </div>
          </div>

          <%= f.hidden_field :union_id, :value => current_user.union.id %>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">ওয়ার্ড নংঃ</label>
            <div class="col-md-9">
              <%= f.number_field :word_no, class: "form-control",placeholder: "In English" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">জাতীয় পরিচয়পত্র নম্বরঃ</label>
            <div class="col-md-9">
              <%= f.text_field :nid, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">জন্ম নিবন্ধন নম্বরঃ</label>
            <div class="col-md-9">
              <%= f.text_field :birthid, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">জন্ম নিবন্ধন নম্বরঃ</label>
            <div class="col-md-9">
              <%= f.collection_select :status,[:active,:pending],:to_s, :to_s,{},{class: "form-control"} %>
            </div>
          </div>


          <div class="form-group">
            <!-- Button -->
            <div class="col-md-offset-3 col-md-9">
              <%= f.submit "Save", class:"btn btn-info" %>
            </div>
          </div>
      <% end %>
      <%= link_to 'Back', requests_citizens_path %>
    </div>
  </div>
</div>

app/views/warishes/index.html.erb
<div class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <p id="notice"><%= notice %></p>

  <h1>ওয়ারিশ সনদ সমূহ</h1>

  <div class="row">
    <div class="form-group col-md-12">
      <% if can? :create, Warish %>
          <%= link_to 'নতুন সনদের আবেদন', new_warish_path, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <%= form_tag(warishes_path, method: :get) do %>
        <div class="form-group col-md-10">
          <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "ওয়ারিশ সনদের নম্বরটি প্রবেশ করুন" %>
        </div>
        <div class="form-group col-md-2">
          <%= submit_tag 'খোঁজ করুন', class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= render 'warishes', warishes: @warishes, show_tracking: false, show_warish_no: true %>
    </div>
  </div>
</div>

app/views/warishes/verify_warish.html.erb
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-2 toppad">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">ওয়ারিশ সনদ যাচাই</h3>
    </div>

    <div class="panel-body">
      <div class="row">

        <%= form_tag(verify_warish_warishes_path, method: :get, remote: true) do %>
            <div class="form-group col-md-10">
              <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "আপনার ওয়ারিশ সনদের নম্বরটি প্রবেশ করুন" %>
            </div>
            <div class="form-group col-md-2">
              <%= submit_tag 'খোঁজ করুন', class: "btn btn-primary" %>
            </div>
        <% end %>
        <div id="results">
          <% if @citizen.present? %>
              <%= render @citizen %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/warishes/verify_warish.js.erb
$("#results").html("<%= escape_javascript render("warish") %>");