config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :cash_books
  resources :citizens do
    member do
      get :edit_request
      get :activate_citizen
      put :permit_request
    end
    collection do
      get :requests
      get :verify_application
      get :verify_citizen
    end
  end

  resources :others_certificates do
    member do
      get :activate
    end
    collection do
      get :requests
      get :verify_application
      get :verify_certificate
    end
  end

  resources :warishes do
    member do
      get :edit_request
      get :activate_warish
      put :permit_request
    end

    collection do
      get :requests
      get :verify_application
      get :verify_warish
    end
  end

  get 'warishes/show_by_tracking_id/:id' => 'warishes#show_by_tracking_id', as: :show_by_tracking_warishes
  get 'citizens/show_by_tracking_id/:id' => 'citizens#show_by_tracking_id', as: :show_by_tracking_citizens
  get 'others_certificates/show_by_tracking_id/:id' => 'others_certificates#show_by_tracking_id', as: :show_by_tracking_certificate

  resources :citizen_requests do
    collection do
      get :search
    end
  end

  resources :forms do
    collection do
      get :tax_or_rate_form
      get :others_form
    end
  end

  resources :collection_moneys

  resources :tax_or_rate_collections do
    collection do
      get :report
    end
  end
  resources :others_collections
  resources :trade_licenses
  resources :profiles

  resources :trade_organizations, shallow: true do

    member do
      get :renew
      post :create_trade_license
      get :print_money_recipt
    end

    collection do
      get :verify
    end
  end

  resources :expenses do
    collection do
      get :report
    end
  end

  get 'trade_organizations/:id/trade_license/:license_id/edit' => 'trade_organizations#edit_license',
      as: :edit_trade_org_trade_license

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  namespace :api do
    resources :divisions do
      member do
        get :districts
      end
    end

    resources :districts do
      member do
        get :upazilas
      end
    end

    resources :upazilas do
      member do
        get :unions
      end
    end

    resources :unions

  end

end

app/models/tax_or_rate_collection.rb
class TaxOrRateCollection < ActiveRecord::Base
  include ApplicationHelper, UnionHelper, CollectionBanglaHelper
  has_one :collection_money, as: :collectable, dependent: :destroy

  accepts_nested_attributes_for :collection_money, :allow_destroy => true
  belongs_to :union
  belongs_to :tax_category

  validates :owners_name, :village_name, :apprisal_no, :owners_name_in_english, presence: true

  def money_senders_name
    self.owners_name
  end

  def init_val(trade_org_id)
    self.tax_year = current_fiscal_year_bangla

    if trade_org_id.present?
      init(TradeOrganization.find(trade_org_id))
    end
  end

  def init(trade_org)
    self.village_name = trade_org.business_place
    self.owners_name = trade_org.owners_name_bng
    self.owners_name_in_english = trade_org.owners_name_eng
    self.apprisal_no = chromic_no trade_org.license_no
    self.tax_category = TaxCategory.first if TaxCategory.first.present?
  end

  def mouja(village_name)
    village_name << ' (' << current_fiscal_year_bangla << ' অর্থবছরের পেশা, ব্যবসা, জীবিকার কর বাবদ' << ')'
  end

  def chromic_no(license_no)
    license_no.split('-').last if license_no.present?
  end

  def category
    return self.tax_category.category_code
  end

  def babod
    return self.tax_category.name if self.tax_category.present?
    String.new
  end

  def comment
    return self.other_reason if self.tax_category.present? && self.tax_category.others?
  end

  def babod_pdf
    babod_val = String.new
    babod_val << bangla_number(self.tax_year) << ' অর্থবছরের ' if self.tax_year.present?
    babod_val << babod
  end

end

app/controllers/tax_or_rate_collections_controller.rb
class TaxOrRateCollectionsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_load_resource :only => [:create]
  before_action :set_tax_rate_collection, only: [:show, :edit, :update, :destroy]

  def index
    # @tax_or_rate_collections = current_user.tax_or_rate_collections.where(status: :active)
    respond_to do |format|
      format.html
      format.json { render json: TaxOrRateCollectionDatatable.new(view_context, current_user) }
    end

  end

  def report
    @start_date = from_date
    @end_date = to_date

    @tax_collections = current_user.tax_or_rate_collections
                           .where(status: :active, :created_at => @start_date.beginning_of_day..@end_date.end_of_day)

    if params[:collections] && params[:collections][:category_id].present?
      @selected_id = params[:collections][:category_id]
      @tax_collections = @tax_collections
                             .where(:tax_category_id => params[:collections][:category_id])
    end

    @total_sum = @tax_collections.map { |s| s.collection_money.total }.reduce(0, :+)
    @tax_sum = @tax_collections.map { |s| s.collection_money.fee }.reduce(0, :+)

    if request.format.html?
      @tax_collections = @tax_collections
                             .page(params[:page])
                             .per(10)
    end

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => file_name_report,
               :template => 'tax_or_rate_collections/index.pdf.erb',
               :layout => 'pdf.html.erb',
               :disposition => 'attachment',
               :show_as_html => params[:debug].present?,
               margin: {top: 10, # default 10 (mm)
                        bottom: 0,
                        left: 5,
                        right: 5},
               dpi: '300'
        #zoom: 1.17647
      end
    end
  end

  def new
    @tax_or_rate_collection = TaxOrRateCollection.new
    @tax_or_rate_collection.build_collection_money
    @tax_or_rate_collection.init_val(params[:trade_org])
  end

  def create
    @tax_or_rate_collection = TaxOrRateCollection.new(tax_or_rate_collections_params)

    respond_to do |format|
      if @tax_or_rate_collection.save
        format.html { redirect_to @tax_or_rate_collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @tax_or_rate_collection }
      else
        format.html { render :new }
        format.json { render json: @tax_or_rate_collection.errors, status: :unprocessable_entity }
      end
    end

  end

  def update

    respond_to do |format|
      if @tax_or_rate_collection.update(tax_or_rate_collections_params)
        format.html { redirect_to @tax_or_rate_collection, notice: 'Collection  was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @tax_or_rate_collection.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    @tax_or_rate_collection.update_attributes(status: :deleted)
    @tax_or_rate_collection.collection_money.remove if @tax_or_rate_collection.collection_money.present?

    respond_to do |format|
      format.html { redirect_to tax_or_rate_collections_path, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => file_name,
               :template => 'tax_or_rate_collections/show.pdf.erb',
               :layout => 'pdf.html.erb',
               :disposition => 'attachment',
               :show_as_html => params[:debug].present?,
               margin: {top: 10, # default 10 (mm)
                        bottom: 0,
                        left: 12,
                        right: 12},
               dpi: '300'
        #zoom: 1.17647
      end
    end

  end

  private

  def set_tax_rate_collection
    @tax_or_rate_collection = TaxOrRateCollection.find(params[:id])
  end

  def tax_or_rate_collections_params
    params.require(:tax_or_rate_collection).permit(:owners_name_in_english, :village_name, :owners_name, :apprisal_no, :union_id, :tax_category_id,
                                                   :other_reason, :tax_year,
                                                   collection_money_attributes: [:id, :fee, :fine, :union_id])
  end


  def file_name
    pdf_file_name 'tax_or_rate_' << @tax_or_rate_collection.union_code
  end

  def file_name_report
    pdf_file_name 'rax_rate_money_collection_'
  end

end

app/helpers/tax_or_rate_collection_helper.rb
module TaxOrRateCollectionHelper

  def show_apprisal?(tax_or_rate_collection)
    return false if tax_or_rate_collection.nil?
    return true if tax_or_rate_collection.apprisal_no.present?
    return false
  end
end

app/views/tax_or_rate_collections/_form.html.erb
<div class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <div class="panel panel-info">
    <div class="panel-heading">
      <div class="panel-title">ট্যাক্স/রেট কালেকশন</div>
    </div>
    <div class="panel-body">

      <%= form_for @tax_or_rate_collection, html: {class: 'form-horizontal'} do |f| %>

          <% if @tax_or_rate_collection.errors.any? %>
              <div id="signupalert" class="alert alert-danger">
                <h2><%= pluralize(@tax_or_rate_collection.errors.count, "error") %> prohibited to save Tax
                  collection</h2>
                <ul>
                  <% @tax_or_rate_collection.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <%= f.hidden_field :union_id, :value => current_user.union.id %>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label"> মালিক/দখলদারের নাম (English)</label>
            <div class="col-md-9">
              <%= f.text_field :owners_name_in_english, class: "form-control", placeholder: "In English" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label"> মালিক/দখলদারের নাম</label>
            <div class="col-md-9">
              <%= f.text_field :owners_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInEng" class="col-md-3 control-label">মৌজার নাম</label>
            <div class="col-md-9">
              <%= f.text_field :village_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInEng" class="col-md-3 control-label">বাবদ</label>
            <div class="col-md-9">
              <%= f.collection_select :tax_category_id, TaxCategory.all,:id,:name,{},{class: "form-control"}%>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInEng" class="col-md-3 control-label">অন্যান্য</label>
            <div class="col-md-9">
              <%= f.text_field :other_reason, class: "form-control", placeholder: "অন্যান্য বাবদ হলে লিখুন" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInEng" class="col-md-3 control-label">অর্থ বছর</label>
            <div class="col-md-9">
              <%= f.text_field :tax_year, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">মূল্যায়ন তালিকার ক্রমিক নং</label>
            <div class="col-md-9">
              <%= f.text_field :apprisal_no, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <%= f.fields_for :collection_money do |cm| %>
              <div class="form-group">
                <label for="nameInBn" class="col-md-3 control-label">গৃহীত অর্থ</label>
                <div class="col-md-9">
                  <%= cm.number_field :fee, class: "form-control", placeholder: "In English number" %>
                </div>
              </div>

              <div class="form-group">
                <label for="nameInBn" class="col-md-3 control-label">জরিমানা(যদি থাকে)</label>
                <div class="col-md-9">
                  <%= cm.number_field :fine, class: "form-control", placeholder: "In English number" %>
                </div>
              </div>
              <%= cm.hidden_field :union_id, :value => current_user.union.id %>

          <% end %>


          <div class="form-group">
            <!-- Button -->
            <div class="col-md-offset-3 col-md-9">
              <%= f.submit :save, class: "btn btn-info" %>
            </div>
          </div>
      <% end %>
      <%= link_to 'Back', tax_or_rate_collections_path %>
    </div>
  </div>
</div>

app/views/tax_or_rate_collections/_results.html.erb
<%= link_to 'pdf', report_tax_or_rate_collections_path(collections: {category_id: get_cat_type }, start_date: params[:start_date], end_date: params[:end_date], format: :pdf), class: "btn" %>

<% if @tax_collections %>
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>রশিদ নং</th>
        <th> জমার তারিখ</th>
        <th>প্রদানকারীর নাম</th>
        <th>বাবদ</th>
        <th>জমার পরিমাণ</th>
        <th>মোট</th>
      </tr>
      </thead>
      <tbody>

      <% @tax_collections.each do |t| %>
          <tr>
            <td><%= t.collection_money.serial_no %></td>
            <td><%= formatted_date_time t.created_at %></td>
            <td><%= t.collection_money.money_senders_name %></td>
            <td><%= t.babod %></td>
            <td><%= t.collection_money.collection_fee %></td>
            <td><%= t.collection_money.total %></td>
          </tr>
      <% end %>
      <tr>
        <td>সর্বমোট</td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= @tax_sum %></td>
        <td><%= @total_sum %></td>
      </tr>
      </tbody>
    </table>
    </tbody>
    </table>
<% end %>
<%= paginate @tax_collections %>

app/views/tax_or_rate_collections/index.html.erb
<div class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <p id="notice"><%= notice %></p>

  <h1>ট্যাক্স/রেট কালেকশন</h1>

  <div class="row">
    <div class="form-group col-md-12">
      <% if can? :create, TaxOrRateCollection %>
          <%= link_to "New", new_tax_or_rate_collection_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <table id="tax_or_rate_collections_table" class="table table-bordered table-striped" data-source="<%= tax_or_rate_collections_path(format: "json") %>">
    <thead>
    <tr>
      <th>Created At</th>
      <th>Owners Name English</th>
      <th>Owners Name</th>
      <th>Village Name</th>
      <th>Total Collection</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/tax_or_rate_collections/index.pdf.erb
<style>

  body {
    font-size: 16px;
    margin: 0 auto;
    background-color: #ffffff;
  }

  .row {
    padding: 0;
    margin: 0;
  }

  th, tr {
    font-weight: normal;
    text-align: center;

  }

  table {
    border: 1px solid black;
    margin: 0;
    padding: 0;
  }

  .table {
    border: 1px solid #000000;
  }

  .table-bordered > thead > tr > th,
  .table-bordered > tbody > tr > th,
  .table-bordered > tfoot > tr > th,
  .table-bordered > thead > tr > td,
  .table-bordered > tbody > tr > td,
  .table-bordered > tfoot > tr > td {
    border: 1px solid #000000;
    margin: 2px;
    padding: 3px;
  }

  table, tr, td, th, tbody, thead, tfoot {
    page-break-inside: avoid;
  }

  thead th {
    background: grey;
    color: white
  }

  [class*='col-'] {
    padding: 0;
    margin: 0;
  }

  p {
    padding: 0;
    margin: 0;
  }

  .margin-left {
    margin-left: 7px;
  }

  .margin-right {
    margin-right: 5px;
  }

  .margin-top-5 {
    margin-top: 5px;
  }

  #margin-top-50 {
    margin-top: 50px;
  }

  .margin-top-10 {
    margin-top: 10px;
  }

</style>

<div>
  <div class="container">

    <div class="row top-header">
      <div class="col-xs-12 text-center">
        <h2><%= bangla_number current_user.union_no %> নং <%= current_user.union_name_bng %> ইউনিয়ন
          পরিষদ</h2>
        <p class="sub"> ডাকঘরঃ <%= current_user.post_name_bng %>
          উপজেলাঃ <%= current_user.upazila_name_bng %>
          জেলাঃ  <%= current_user.zila_name_bng %></p>
      </div>
    </div>

    <div class="row text-center">
      <h3><u><%= 'ট্যাক্স ও রেট কালেকশন'%></u></h3>
    </div>
    <div class="row">
      <div class="col-xs-6">
        <div class="row">
          <div class="col-xs-3 trade-label">
            <p>Start Date</p>
          </div>
          <div class="col-xs-9">
            <p class="margin-left" id="license_no"><%= formatted_date_time @start_date %></p>
          </div>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="row">
          <div class="col-xs-3 trade-label">
            <p>End Date</p>
          </div>
          <div class="col-xs-9">
            <p class="pull-left margin-left"><%= formatted_date_time @end_date %></p>
          </div>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-xs-12  margin-top-10">

        <% if @tax_collections %>
            <table class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>রশিদ নং</th>
                <th> জমার তারিখ</th>
                <th>প্রদানকারীর নাম</th>
                <th>বাবদ</th>
                <th>জমার পরিমাণ</th>
                <th>মোট</th>
              </tr>
              </thead>
              <tbody>

              <% @tax_collections.each do |t| %>
                  <tr>
                    <td><%= t.collection_money.serial_no %></td>
                    <td><%= formatted_date_time t.created_at %></td>
                    <td><%= t.collection_money.money_senders_name %></td>
                    <td><%= t.babod %></td>
                    <td><%= t.collection_money.collection_fee %></td>
                    <td><%= t.collection_money.total %></td>
                  </tr>
              <% end %>
              <tr>
                <td>সর্বমোট</td>
                <td></td>
                <td></td>
                <td></td>
                <td><%= @tax_sum %></td>
                <td><%= @total_sum %></td>
              </tr>
              </tbody>
            </table>
            </tbody>
            </table>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/tax_or_rate_collections/report.html.erb
<div class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <p id="notice"><%= notice %></p>
  <h2>ট্যাক্স ও রেট কালেকশন</h2>

  <%= form_tag(report_tax_or_rate_collections_path, class: "form-inline", method: :get) do %>

      <%= render 'layouts/search_box' %>

      <div class="form-group">
        <%= collection_select(:collections, :category_id, TaxCategory.all, :id, :name, {:include_blank => 'সব', :selected => @selected_id}, {class: "form-control"}) %>
      </div>
      <%= submit_tag :Search, class: "btn btn-primary" %>
  <% end %>
  <div id="results">
    <%= render 'results' %>
  </div>
</div>

app/views/tax_or_rate_collections/show.html.erb
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
  <p id="notice"><%= notice %></p>
  <% if @tax_or_rate_collection.present? %>

      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @tax_or_rate_collection.owners_name_in_english %></h3>
        </div>
        <div class="panel-body">
          <div class="row">

            <div class=" col-md-9 col-lg-9 ">
              <table class="table table-user-information">
                <tbody>
                <tr>
                  <td>মালিক/দখলদারের নাম</td>
                  <td><%= @tax_or_rate_collection.owners_name %></td>
                </tr>

                <tr>
                  <td>মৌজার নাম</td>
                  <td><%= @tax_or_rate_collection.village_name %></td>
                </tr>
                <tr>
                  <td>মূল্যায়ন তালিকার ক্রমিক নং</td>
                  <td><%= @tax_or_rate_collection.apprisal_no %></td>
                </tr>
                <tr>
                  <td>গৃহীত অর্থ</td>
                  <td><%= @tax_or_rate_collection.collection_money.fee %></td>
                </tr>

                <tr>
                  <td>জরিমানা(যদি থাকে)</td>
                  <td><%= @tax_or_rate_collection.collection_money.fine %></td>
                </tr>

                <tr>
                  <td>সর্বমোট</td>
                  <td><%= @tax_or_rate_collection.collection_money.total %></td>
                </tr>

                </tr>

                </tbody>
              </table>

              <%= link_to 'Download', tax_or_rate_collection_path(@tax_or_rate_collection,format: 'pdf'), class: "btn btn-info btn-default" %>
              <%= link_to 'Back', tax_or_rate_collections_path, class: "btn btn-primary" %>

            </div>
          </div>
        </div>
      </div>
  <% end %>

</div>

app/views/tax_or_rate_collections/show.pdf.erb
<style>

  body {
    font-size: 18px;
    margin: 0 auto;
    background-color: #ffffff;
  }

  .row {
    padding: 0;
    margin: 0;
  }

  [class*='col-'] {
    padding: 0;
    margin: 0;
  }

  p {
    padding: 0;
    margin: 0;
  }

  .margin-left {
    margin-left: 7px;
  }

  .margin-right {
    margin-right: 5px;
  }

  .margin-top-5 {
    margin-top: 5px;
  }

  #margin-top-50 {
    margin-top: 50px;
  }

  .margin-top-7 {
    margin-top: 7px;
  }

</style>

<div>
  <div class="container">

    <div class="row top-header">
      <div class="col-xs-12 text-center">
        <h2><%= bangla_number @tax_or_rate_collection.union_no %> নং <%= @tax_or_rate_collection.union_name_bng %>
          ইউনিয়ন
          পরিষদ</h2>
        <p class="sub"> ডাকঘরঃ <%= @tax_or_rate_collection.post_name_bng %>
          উপজেলাঃ <%= @tax_or_rate_collection.upazila_name_bng %>
          জেলাঃ  <%= @tax_or_rate_collection.zila_name_bng %></p>
      </div>
    </div>

    <div class="row ">
      <div class="col-xs-12">
        <p class="text-center">ইউপি ফরম-৩</p>
      </div>
    </div>
    <div class="row ">
      <div class="col-xs-12">
        <p class="text-center">[ বিধি ৮ দ্রষ্টব্য ]</p>
      </div>
    </div>
    <div class="row ">
      <div class="col-xs-12">
        <p class="text-center">কর ও রেইট আদায়ের রশিদ</p>
      </div>
    </div>


    <div class="row margin-top-5">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4 trade-label">
            <p>ক্রমিক নং</p>
          </div>
          <div class="col-xs-8">
            <p class="margin-left"><%= @tax_or_rate_collection.serial_no_bangla %></p>
          </div>
        </div>
      </div>
    </div>


    <div class="row margin-top-5">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4 trade-label">
            <p>মৌজার নাম</p>
          </div>
          <div class="col-xs-8">
            <p class="margin-left"><%= @tax_or_rate_collection.village_name %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row margin-top-5">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4 trade-label">
            <p>মালিক/দখলদারের নাম</p>
          </div>
          <div class="col-xs-8">
            <p class="margin-left"><%= @tax_or_rate_collection.owners_name %></p>
          </div>
        </div>
      </div>
    </div>

    <% if @tax_or_rate_collection.tax_category.present? %>
        <div class="row margin-top-5">
          <div class="col-xs-12">
            <div class="row">
              <div class="col-xs-4 trade-label">
                <p>বাবদ</p>
              </div>
              <div class="col-xs-8">
                <p class="margin-left"><%= @tax_or_rate_collection.babod_pdf %></p>
              </div>
            </div>
          </div>
        </div>
    <% end %>

    <div class="row margin-top-5">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4 trade-label">
            <p>মূল্যায়ন তালিকার ক্রমিক নং</p>
          </div>
          <div class="col-xs-8">
            <p class="margin-left"><%= bangla_number @tax_or_rate_collection.apprisal_no %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row margin-top-5">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4 trade-label">
            <p>গৃহীত অর্থ</p>
          </div>
          <div class="col-xs-8">
            <p class="margin-left"><%= @tax_or_rate_collection.fee_bangla %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row margin-top-5">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4 trade-label">
            <p>জরিমানা(যদি থাকে)</p>
          </div>
          <div class="col-xs-8">
            <p class="margin-left"><%= @tax_or_rate_collection.fine_bangla %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row margin-top-5">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4 trade-label">
            <p>মোট টাকা</p>
          </div>
          <div class="col-xs-8">
            <p class="margin-left"><%= @tax_or_rate_collection.total_bangla %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row" id="margin-top-50">
      <div class="col-xs-6">
        <div>
          <p>তারিখ: <%= bangla_date Time.now %></p>
        </div>
        <div>
          <p>সময়: <%= bangla_time Time.now %></p>
        </div>
      </div>
      <div class="col-xs-6">
        <div>
          <p class="text-center">আদায়কারীর স্বাক্ষর</p>
        </div>
      </div>
    </div>
  </div>
</div>