config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :cash_books
  resources :citizens do
    member do
      get :edit_request
      get :activate_citizen
      put :permit_request
    end
    collection do
      get :requests
      get :verify_application
      get :verify_citizen
    end
  end

  resources :others_certificates do
    member do
      get :activate
    end
    collection do
      get :requests
      get :verify_application
      get :verify_certificate
    end
  end

  resources :warishes do
    member do
      get :edit_request
      get :activate_warish
      put :permit_request
    end

    collection do
      get :requests
      get :verify_application
      get :verify_warish
    end
  end

  get 'warishes/show_by_tracking_id/:id' => 'warishes#show_by_tracking_id', as: :show_by_tracking_warishes
  get 'citizens/show_by_tracking_id/:id' => 'citizens#show_by_tracking_id', as: :show_by_tracking_citizens
  get 'others_certificates/show_by_tracking_id/:id' => 'others_certificates#show_by_tracking_id', as: :show_by_tracking_certificate

  resources :citizen_requests do
    collection do
      get :search
    end
  end

  resources :forms do
    collection do
      get :tax_or_rate_form
      get :others_form
    end
  end

  resources :collection_moneys

  resources :tax_or_rate_collections do
    collection do
      get :report
    end
  end
  resources :others_collections
  resources :trade_licenses
  resources :profiles

  resources :trade_organizations, shallow: true do

    member do
      get :renew
      post :create_trade_license
      get :print_money_recipt
    end

    collection do
      get :verify
    end
  end

  resources :expenses do
    collection do
      get :report
    end
  end

  get 'trade_organizations/:id/trade_license/:license_id/edit' => 'trade_organizations#edit_license',
      as: :edit_trade_org_trade_license

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  namespace :api do
    resources :divisions do
      member do
        get :districts
      end
    end

    resources :districts do
      member do
        get :upazilas
      end
    end

    resources :upazilas do
      member do
        get :unions
      end
    end

    resources :unions

  end

end

app/models/trade_organization.rb
class TradeOrganization < ActiveRecord::Base
  include ApplicationHelper,UnionHelper

  belongs_to :union
  has_many :trade_licenses, dependent: :destroy
  accepts_nested_attributes_for :trade_licenses,:allow_destroy => true
  validates_uniqueness_of :license_no,scope: :union
  after_create :save_license_no,:save_nid_birthid_as_english

  validates :enterprize_name_in_eng,:enterprize_name_in_bng,
            :owners_name_eng,:owners_name_bng,
            :fathers_name,:mothers_name,
            :village_name,:post_name,
            :upazilla_name,:zilla_name,:word_no,
            :business_place,:business_category,
            presence: true

  def address
      self.village_name << ',' << self.upazilla_name << ',' << self.zilla_name
  end


  def barcode
    barcode = String.new
    barcode << self.license_no if self.license_no.present?
    barcode
  end

  def latest_trade_license
    @trade_license ||= self.trade_licenses.order('fiscal_year desc').first
  end

  def fee
    return String.new unless latest_trade_license.present?
    taka = bangla_number latest_trade_license.license_fee.to_s
    taka << ' টাকা মাত্র ।'
  end

  def license_deadline
    return String.new unless latest_trade_license.present?
    latest_trade_license.fiscal_year
  end

  def license_serial_no
    return String.new unless latest_trade_license.present?
    bangla_number latest_trade_license.id.to_s
  end

  def deadline
    return String.new unless latest_trade_license.present?
    latest_trade_license.deadline
  end

  def deadline_top
    return String.new unless latest_trade_license.present?
    latest_trade_license.deadline_top
  end

  def fiscal_year
    return String.new unless latest_trade_license.present?
    latest_trade_license.fiscal_year_show
  end


  def license_fee
    fee_number_decimal latest_trade_license.license_fee
  end

  def total_fee
    fee_number_decimal latest_trade_license.total_fee
  end

  def fine
    fee_number_decimal latest_trade_license.fine_fee
  end

  def remain
    fee_number_decimal latest_trade_license.remaining_fee
  end

  def vat
    fee_number_decimal latest_trade_license.vat
  end

  def money_collection_serial_no
    bangla_number latest_trade_license.money_collection_serial_no.to_s
  end

  def word_no_bn
    return String.new unless word_no.present?
    bangla_number word_no.to_s
  end

  def nid_or_birthid
    return '-' unless self.nid.present? || self.birthid.present?
    return bangla_number self.nid if self.nid.present?
    return bangla_number self.birthid if self.birthid.present?
  end

  private

  def save_license_no
    license_no = self.union.union_code << '-'<< current_year_month_day.to_s << '-' << max_count.to_s
    self.update_attributes(:license_no => license_no)
  end

  def save_nid_birthid_as_english
    self.nid = english_number(nid) if nid.present?
    self.birthid = english_number(birthid) if birthid.present?
  end

  def max_count
    count = TradeOrganization.where(union_id: self.union.id).count
    count
  end

  def fee_number(number)
    taka = '0'
    taka = number.to_s if number.present?
    bangla_number taka << '.00'
  end

  def fee_number_decimal(number)
    taka =  number.present? ? number : 0
    taka = '%.2f' % taka
    bangla_number taka.to_s
  end

end

app/controllers/trade_organization_controller.rb
class TradeOrganizationController < ApplicationController
  before_action :authenticate_user!

  def index

  end

  def new

  end

  def create

  end

  def renew

  end

  private
  def trade_organization_params
    params.require(:trade_organization).permit(:name)
  end

end

app/controllers/trade_organizations_controller.rb
class TradeOrganizationsController < ApplicationController
  require 'barby'
  require 'barby/barcode'
  require 'barby/barcode/qr_code'
  require 'barby/outputter/png_outputter'

  include ApplicationHelper
  before_action :authenticate_user!, except: [:verify]
  load_and_authorize_resource
  skip_authorize_resource :only => [:print_money_recipt,:verify]
  before_action :set_trade_organization, only: [:show, :edit, :update, :destroy,
                                                :renew, :show_money_recipt,
                                                :create_trade_license, :edit_license]

  def index
    respond_to do |format|
      format.html
      format.json { render json: TradeOrganizationDatatable.new(view_context, current_user) }
    end

  end

  def new
    @trade_organization = TradeOrganization.new
    trade_licenses = @trade_organization.trade_licenses.build
    trade_licenses.build_collection_money
    #logger.debug("Trade liv",trade_licenses)
  end

  def show
    @barcode = barcode_output(@trade_organization) if params[:format] == 'pdf'

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => file_name,
               :template => 'trade_organizations/show.pdf.erb',
               :layout => 'pdf.html.erb',
               :disposition => 'attachment',
               :show_as_html => params[:debug].present?,
               margin: {top: 2, # default 10 (mm)
                        bottom: 0,
                        left: 17,
                        right: 0},
               dpi: '300'
        #zoom: 1.17647
      end
    end
  end

  def barcode_output(trade_organization)
    barcode_string = trade_organization.barcode
    barcode = Barby::QrCode.new(barcode_string, level: :q, size: 6)
    # PNG OUTPUT
    base64_output = Base64.encode64(barcode.to_png({xdim: 3}))
    "data:image/png;base64,#{base64_output}"
  end

  def print_money_recipt
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => money_recipt_file_name,
               :template => 'trade_organizations/print_money_recipt.pdf.erb',
               :layout => 'pdf.html.erb',
               :disposition => 'attachment',
               :show_as_html => params[:debug].present?,
               margin: {top: 10, # default 10 (mm)
                        bottom: 0,
                        left: 12,
                        right: 12},
               dpi: '300'
        #zoom: 1.17647
      end
    end

  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @trade_organization = TradeOrganization.new(trade_organization_params)

    respond_to do |format|
      if @trade_organization.save
        format.html { redirect_to @trade_organization, notice: 'Trade License was successfully created.' }
        format.json { render :show, status: :created, location: @trade_organization }
      else
        format.html { render :new }
        format.json { render json: @trade_organization.errors, status: :unprocessable_entity }
      end
    end

  end

  def create_trade_license
    @trade_license = TradeLicense.new(trade_license_params)
    @trade_organization.trade_licenses.push @trade_license

    respond_to do |format|
      if @trade_license.save
        format.html { redirect_to @trade_organization, notice: 'was successfully created.' }
        format.json { render :show, status: :created, location: @trade_organization }
      else
        format.html { render :renew }
        format.json { render json: @trade_organization.errors, status: :unprocessable_entity }
      end
    end

  end

  def update_trade_license

  end


  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @trade_organization.update(trade_organization_params)
        format.html { redirect_to @trade_organization, notice: 'Trade License was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @trade_organization.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @trade_organization.update_attributes(status: :deleted)

    if @trade_organization.trade_licenses.present?
      @trade_organization.trade_licenses.each do |tl|
        tl.remove
      end
    end

    respond_to do |format|
      format.html { redirect_to trade_organizations_url, notice: 'Trade Lisence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def renew
    @trade_license = TradeLicense.new
    @trade_license.build_collection_money
  end

  def edit_license
    @trade_license = TradeLicense.find(params[:license_id])
  end

  def update_issue_date
    #TODO: ajax for update issue date
  end

  def verify
    @trade_organization = TradeOrganization.find_by_license_no(params[:q]) if params[:q]

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def file_name
    pdf_file_name 'trade_license_' << @trade_organization.union_code
  end

  def money_recipt_file_name
    pdf_file_name 'money_recipt_' << @trade_organization.union_code
  end

  def set_trade_organization
    @trade_organization = current_user.trade_organizations.find(params[:id])
  end

  def trade_organization_params
    params.require(:trade_organization).permit(:enterprize_name_in_eng, :enterprize_name_in_bng,
                                               :owners_name_eng, :owners_name_bng,
                                               :fathers_name, :mothers_name, :spouse_name,
                                               :village_name, :post_name, :upazilla_name, :word_no,
                                               :zilla_name, :business_place, :business_category, :holding_no, :nid, :birthid,
                                               :union_id, trade_licenses_attributes:
                                                   [:fiscal_year, collection_money_attributes: [:fee, :remain, :fine, :vat, :union_id]])
  end

  def trade_license_params
    params.require(:trade_license).permit(:fiscal_year, collection_money_attributes: [:fee, :remain, :fine, :vat, :union_id])
  end

end

app/helpers/trade_organization_helper.rb
module TradeOrganizationHelper
  def current_fiscal_year
    now = Time.now
    year = now.year
    year = now.year - 1 if now.month < 7 #if fiscal year less than june
    year.to_s
  end
end

app/views/trade_organizations/_form.html.erb
<div id="signupbox" class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <div class="panel panel-info">
    <div class="panel-heading">
      <div class="panel-title">ট্রেড লাইসেন্স ফরম</div>
    </div>
    <div class="panel-body">
      <%= form_for @trade_organization, html: {class: 'form-horizontal'} do |f| %>

          <% if @trade_organization.errors.any? %>
              <div id="signupalert" class="alert alert-danger">
                <h2><%= pluralize(@trade_organization.errors.count, "error") %> prohibited to save Trade License</h2>
                <ul>
                  <% @trade_organization.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="form-group">
            <label for="nameInEng" class="col-md-3 control-label">প্রতিষ্ঠানের নামঃ(ইংরেজি)</label>
            <div class="col-md-9">
              <%= f.text_field :enterprize_name_in_eng, class: "form-control", placeholder: "Name In English" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">প্রতিষ্ঠানের নামঃ(বাংলা)</label>
            <div class="col-md-9">
              <%= f.text_field :enterprize_name_in_bng, class: "form-control", placeholder: "Name In Bangla" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">সত্ত্বাধিকারীর নামঃ (ইংরেজি)</label>
            <div class="col-md-9">
              <%= f.text_field :owners_name_eng, class: "form-control", placeholder: "In English" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label"> সত্ত্বাধিকারীর নামঃ (বাংলা)</label>
            <div class="col-md-9">
              <%= f.text_field :owners_name_bng, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">পিতার নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :fathers_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">মাতার নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :mothers_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">স্বামী/স্ত্রীর নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :spouse_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <%= f.hidden_field :union_id, :value => current_user.union.id %>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">গ্রামের নামঃ</label>
            <div class="col-md-9">
              <%= f.text_field :village_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">ডাকঘরঃ</label>
            <div class="col-md-9">
              <%= f.text_field :post_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">উপজেলাঃ</label>
            <div class="col-md-9">
              <%= f.text_field :upazilla_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">জেলা</label>
            <div class="col-md-9">
              <%= f.text_field :zilla_name, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <span class=" text-center help-block">নাগরিকত্ব নম্বর অথবা জন্ম নিবন্ধন নম্বর যেকোন একটি দিলে হবে</span>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">জাতীয় পরিচয়পত্র নম্বরঃ</label>
            <div class="col-md-9">
              <%= f.text_field :nid, class: "form-control" %>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">জন্ম নিবন্ধন নম্বরঃ</label>
            <div class="col-md-9">
              <%= f.text_field :birthid, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">ব্যবসার স্থানঃ</label>
            <div class="col-md-9">
              <%= f.text_field :business_place, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">ওয়ার্ড নম্বরঃ</label>
            <div class="col-md-9">
              <%= f.number_field :word_no, class: "form-control", placeholder: "In English Number" %>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">দোকান/হোল্ডিং নং</label>
            <div class="col-md-9">
              <%= f.text_field :holding_no, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label"> ব্যবসার ধরনঃ</label>
            <div class="col-md-9">
              <%= f.text_field :business_category, class: "form-control", placeholder: "In Bangla" %>
            </div>
          </div>

          <%= f.fields_for :trade_licenses do |trade_license_form| %>
              <div class="form-group">
                <label for="nameInBn" class="col-md-3 control-label"> অর্থ বছরঃ</label>
                <div class="col-md-9">
                  <%= trade_license_form.number_field :fiscal_year,value: current_fiscal_year, class: "form-control", placeholder: "In English" %>
                  <span class="help-block">অর্থবছরের প্রথম বছরটি লিখুন । ২০১৬-২০১৭ অর্থবছর হলে শুধু ২০১৬ লিখুন (ইংরেজিতে)</span>
                </div>
              </div>
              <%= trade_license_form.fields_for :collection_money do |cm| %>
                  <div class="form-group">
                    <label for="nameInBn" class="col-md-3 control-label"> লাইসেন্স ফিঃ</label>
                    <div class="col-md-9">
                      <%= cm.number_field :fee, class: "form-control", placeholder: "In English number" %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="nameInBn" class="col-md-3 control-label">বকেয়া</label>
                    <div class="col-md-9">
                      <%= cm.number_field :remain, class: "form-control", placeholder: "In English number" %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="nameInBn" class="col-md-3 control-label">জরিমানা/অন্যান্য</label>
                    <div class="col-md-9">
                      <%= cm.number_field :fine, class: "form-control", placeholder: "In English number" %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="nameInBn" class="col-md-3 control-label">ভ্যাট</label>
                    <div class="col-md-9">
                      <%= cm.number_field :vat, class: "form-control", placeholder: "In English number" %>
                    </div>
                  </div>

                  <%= cm.hidden_field :union_id, :value => current_user.union.id %>
              <% end %>

          <% end %>

          <div class="form-group">
            <!-- Button -->
            <div class="col-md-offset-3 col-md-9">
              <%= f.submit "Save", class: "btn btn-info" %>

            </div>
          </div>
      <% end %>
      <%= link_to 'Back', trade_organizations_path %>
    </div>
  </div>
</div>

app/views/trade_organizations/_renew_form.html.erb
<div class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <div class="panel panel-info">
    <div class="panel-heading">
      <div class="panel-title"><%= @trade_organization.enterprize_name_in_eng %></div>
    </div>
    <div class="panel-body">
      <!--<form id="citizenform" class="form-horizontal" role="form">-->
      <%= form_for @trade_license, html: {class: 'form-horizontal'}, url: create_trade_license_trade_organization_path do |f| %>

          <% if @trade_license.errors.any? %>
              <div id="signupalert" class="alert alert-danger">
                <h2><%= pluralize(@trade_license.errors.count, "error") %> prohibited to renew Trade License</h2>
                <ul>
                  <% @trade_license.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="form-group">
            <label for="nameInEng" class="col-md-3 control-label">প্রতিষ্ঠানের নাম (ইংরেজি)</label>
            <div class="col-md-9">
              <input type="text" class="form-control" name="nameInEng" placeholder="Name In English"
                     disabled="true" value="<%= @trade_organization.enterprize_name_in_eng %>"/>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">প্রতিষ্ঠানের নাম (বাংলা)</label>
            <div class="col-md-9">
              <input type="text" class="form-control" name="nameInEng" placeholder="Name In English"
                     disabled="true" value="<%= @trade_organization.enterprize_name_in_bng %>"/>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInEng" class="col-md-3 control-label">সত্ত্বাধিকারীর নামঃ</label>
            <div class="col-md-9">
              <input type="text" class="form-control" name="nameInEng" placeholder="Name In English"
                     disabled="true" value="<%= @trade_organization.owners_name_bng %>"/>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">ব্যবসার স্থানঃ</label>
            <div class="col-md-9">
              <input type="text" class="form-control" name="nameInEng" placeholder="Name In English"
                     disabled="true" value="<%= @trade_organization.business_place %>"/>
            </div>
          </div>

          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">ব্যবসার ধরনঃ</label>
            <div class="col-md-9">
              <input type="text" class="form-control" name="nameInEng" placeholder="Name In English"
                     disabled="true" value="<%= @trade_organization.business_category %>"/>
            </div>
          </div>


          <div class="form-group">
            <label for="nameInBn" class="col-md-3 control-label">অর্থ বছরঃ</label>
            <div class="col-md-9">
              <%= f.number_field :fiscal_year,value: current_fiscal_year, class: "form-control", placeholder: "In English number" %>
              <span class="help-block">অর্থবছরের প্রথম বছরটি লিখুন । ২০১৬-২০১৭ অর্থবছর হলে শুধু ২০১৬ লিখুন (ইংরেজিতে)</span>
            </div>
          </div>
          <%= f.fields_for :collection_money do |cm| %>

              <div class="form-group">
                <label for="nameInBn" class="col-md-3 control-label">লাইসেন্স নবায়ন ফিঃ</label>
                <div class="col-md-9">
                  <%= cm.number_field :fee, class: "form-control", placeholder: "In English number" %>
                </div>
              </div>

              <div class="form-group">
                <label for="nameInBn" class="col-md-3 control-label">বকেয়া</label>
                <div class="col-md-9">
                  <%= cm.number_field :remain, class: "form-control", placeholder: "In English number" %>
                </div>
              </div>


              <div class="form-group">
                <label for="nameInBn" class="col-md-3 control-label">জরিমানা/অন্যান্য</label>
                <div class="col-md-9">
                  <%= cm.number_field :fine, class: "form-control", placeholder: "In English number" %>
                </div>
              </div>

              <div class="form-group">
                <label for="nameInBn" class="col-md-3 control-label">ভ্যাট</label>
                <div class="col-md-9">
                  <%= cm.number_field :vat, class: "form-control", placeholder: "In English number" %>
                </div>
              </div>
              <%= cm.hidden_field :union_id, :value => current_user.union.id %>
          <% end %>


          <div class="form-group">
            <!-- Button -->
            <div class="col-md-offset-3 col-md-9">
              <%= f.submit :save, class: "btn btn-info" %>
            </div>
          </div>
      <% end %>
      <%= link_to 'Back', trade_organization_path(@trade_organization) %>
    </div>

  </div>
</div>

app/views/trade_organizations/edit_license.html.erb
<%= render 'renew_form' %>

app/views/trade_organizations/show.html.erb
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
  <p id="notice"><%= notice %></p>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @trade_organization.enterprize_name_in_eng %></h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class=" col-md-9 col-lg-9 ">
          <table class="table table-user-information">
            <tbody>
            <tr>
              <td>লাইসেন্স নং</td>
              <td><%= @trade_organization.license_no %></td>
            </tr>

            <tr>
              <td>প্রতিষ্ঠানের নামঃ</td>
              <td><%= @trade_organization.enterprize_name_in_bng %></td>
            </tr>
            <tr>
              <td>স্বত্বাধীকারির নামঃ</td>
              <td><%= @trade_organization.owners_name_bng %></td>
            </tr>

            <tr>
              <td>ব্যবসার স্থানঃ</td>
              <td><%= @trade_organization.business_place %></td>
            </tr>
            <tr>
              <td>ব্যবসার ধরনঃ</td>
              <td><%= @trade_organization.business_category %></td>
            </tr>

            <% if @trade_organization.trade_licenses.count > 0 %>

                <tr>
                  <td>সর্বশেষ নবায়ন বছরঃ</td>
                  <td><%= @trade_organization.trade_licenses.order('fiscal_year desc').first.fiscal_year %></td>
                </tr>
            <% end %>

            </tbody>
          </table>


        </div>
      </div>

      <div class="row">
        <div class=" col-md-12 col-lg-12 ">

          <%= link_to 'Print Certificate', trade_organization_path(@trade_organization, format: 'pdf'), class: "btn btn-success" %>
          <%= link_to 'Print Money Receipt', print_money_recipt_trade_organization_path(@trade_organization, format: 'pdf'), class: "btn btn-info" %>


          <% if can? :create, TradeLicense %>
              <%= link_to 'Renew License', renew_trade_organization_path(@trade_organization), class: "btn btn-primary" %>
          <% end %>

          <%= link_to 'Tax Rate', new_tax_or_rate_collection_path(trade_org: @trade_organization), class: "btn btn-info" %>
        </div>
      </div>

    </div>


  </div>
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Trade Licenses</h3>
    </div>

    <div class="panel-body">
      <div class="row">

        <div class=" col-md-12 col-lg-12 ">

          <table class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>Fiscal Year</th>
              <th>License Fee</th>
              <th>Created</th>
              <% if can? :manage, TradeLicense %>
                  <th></th>
              <% end %>
            </tr>
            </thead>
            <tbody>
            <% @trade_organization.trade_licenses.order('fiscal_year desc').each do |trade_license| %>
                <tr>
                  <td><%= trade_license.fiscal_year_show_eng %></td>
                  <td><%= trade_license.license_fee %></td>
                  <td><%= trade_license.created_at.strftime "%B %e, %Y" %></td>
                  <% if can? :manage, TradeLicense %>
                      <td>
                        <%= link_to "Edit", edit_trade_license_path(trade_license) %>
                        <%= link_to "Delete", trade_license_path(trade_license), method: :delete, data: {confirm: 'Are you sure?'} %>
                      </td>
                  <% end %>
                </tr>
            <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/trade_organizations/verify.js.erb
$("#results").html("<%= escape_javascript render("trade_organization") %>");